(()=>{"use strict";const D=window.JSKILLS_DATA;let grade=+document.body.dataset.grade,topics=D[grade],current=null,qi=0,score=0;const $=id=>document.getElementById(id);
function openTopic(i){current=topics[i];qi=0;score=0;renderTopic();location.hash="topic"}
function renderTopic(){$("topicTitle").textContent=current.topic;$("topicSubject").textContent=current.icon+" "+current.subject;$("sim").innerHTML=current.simulation;initSim($("sim").querySelector(".simbox"));$("quizBox").classList.add("hidden");$("topicView").classList.remove("hidden")}
function initSim(box){const c=box.querySelector("canvas"),x=c.getContext("2d"),controls=box.querySelector(".controls"),kind=box.dataset.kind;controls.innerHTML="";
const add=(label,min,max,val,step,cb)=>{let l=document.createElement("label");l.innerHTML=`${label} <input type="range" min="${min}" max="${max}" value="${val}" step="${step}"><b>${val}</b>`;let inp=l.querySelector("input"),b=l.querySelector("b");inp.oninput=()=>{b.textContent=inp.value;cb(+inp.value)};controls.appendChild(l);return +inp.value};
let a=5,b=5;
function draw(){x.clearRect(0,0,c.width,c.height);x.fillStyle="#f8fafc";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#cfd8e6";x.lineWidth=1;
if(kind==="Mathematics"){for(let i=0;i<11;i++){let px=50+i*62;x.beginPath();x.moveTo(px,40);x.lineTo(px,290);x.stroke();x.fillStyle="#52627a";x.fillText(i-5,px-5,315)}let y=165-a*18;x.fillStyle="#5875ad";x.beginPath();x.arc(360,Math.max(45,Math.min(280,y)),14,0,7);x.fill();x.fillText("Number / value = "+a,280,30)}
else if(kind==="English"){x.fillStyle="#17233b";x.font="bold 26px system-ui";x.fillText("EVIDENCE",45,90);x.font="18px system-ui";x.fillStyle="#5875ad";x.fillText("Claim",45,145);x.fillStyle="#17233b";x.fillText("→",160,145);x.fillStyle="#5875ad";x.fillText("Evidence",210,145);x.fillStyle="#17233b";x.fillText("→",350,145);x.fillStyle="#5875ad";x.fillText("Explanation",400,145);x.font="14px system-ui";x.fillStyle="#65738a";x.fillText("Move the evidence strength slider and observe the support score.",45,210);x.fillStyle="#17233b";x.fillText("Support score: "+(a*10)+" / 100",45,250)}
else if(kind==="Social Science"){x.strokeStyle="#9eb0c9";x.lineWidth=2;for(let i=0;i<6;i++){x.beginPath();x.arc(170+i*75,160,70,0,7);x.stroke()}x.fillStyle="#5875ad";x.beginPath();x.arc(170+a*50,160,12,0,7);x.fill();x.fillStyle="#17233b";x.fillText("Timeline / map position: "+a,45,285)}
else if(kind==="Physics"){let v=a*10; x.strokeStyle="#9eb0c9";x.beginPath();x.moveTo(55,260);x.lineTo(665,260);x.stroke();x.fillStyle="#5875ad";x.beginPath();x.arc(80+v*5,260,15,0,7);x.fill();x.fillStyle="#17233b";x.fillText("Variable = "+v+"  •  model response = "+(v*2),55,50)}
else if(kind==="Chemistry"){x.fillStyle="#17233b";x.fillText("Particles / ions",50,40);for(let i=0;i<22;i++){let px=80+(i%11)*55,py=85+Math.floor(i/11)*80+(a%3)*10;x.fillStyle=i%2?"#5875ad":"#9aaac0";x.beginPath();x.arc(px,py,14,0,7);x.fill()}x.fillStyle="#17233b";x.fillText("Concentration level: "+a,50,260)}
else if(kind==="Botany"){x.strokeStyle="#5875ad";x.lineWidth=7;x.beginPath();x.moveTo(360,285);x.lineTo(360,90);x.stroke();for(let i=0;i<5;i++){x.fillStyle="#86a873";x.beginPath();x.ellipse(330+i%2*60,210-i*28,45,18,i%2?-.4:.4,0,7);x.fill()}x.fillStyle="#17233b";x.fillText("Light level: "+a+"  •  photosynthesis model: "+(a*10)+"%",45,40)}
else {x.fillStyle="#5875ad";x.beginPath();x.arc(360,165,80,0,7);x.fill();x.fillStyle="#fff";x.fillText("SYSTEM",330,170);x.fillStyle="#17233b";x.fillText("Input level: "+a,45,285)}
}
add(kind==="Mathematics"?"Number value":kind==="Physics"?"Motion / field":kind==="Chemistry"?"Concentration":kind==="Botany"?"Light":kind==="English"?"Evidence strength":"Position / input",1,10,5,1,v=>{a=v;draw()});add("Observation",1,10,5,1,v=>{b=v;draw()});draw()}
function startQuiz(){$("quizBox").classList.remove("hidden");$("topicView").scrollIntoView({behavior:"smooth"});renderQ()}
function renderQ(){let q=current.questions[qi];$("qcount").textContent=`Question ${qi+1} / 20`;$("qtext").textContent=q.q;$("opts").innerHTML=q.o.map((o,i)=>`<label class="opt"><input type="radio" name="ans" value="${i}">${String.fromCharCode(65+i)}. ${o}</label>`).join("")}
function submitQ(){let a=document.querySelector('input[name=ans]:checked');if(!a)return alert("Choose the best answer.");if(+a.value===current.questions[qi].a)score++;if(qi<19){qi++;renderQ()}else finish()}
function finish(){let pct=score*5,level=pct<50?"Remedial":pct<65?"Developing":pct<80?"On Track":"Advanced";$("result").innerHTML=`<div class="result"><b>${pct}%</b><span>${level}</span><p>${pct>=80?"Great. Consider advanced / Olympiad / NEET Foundation practice where applicable.":pct<50?"Teacher intervention recommended with targeted re-learning and re-test.":"Continue guided practice and monitor the next assessment."}</p></div>`;$("quizBox").classList.add("hidden");$("result").classList.remove("hidden");}
function goHome(){location.href="../index.html"}window.openTopic=openTopic;window.startQuiz=startQuiz;window.submitQ=submitQ;window.goHome=goHome;window.addEventListener("DOMContentLoaded",()=>{let grid=$("topicGrid");grid.innerHTML=topics.map((t,i)=>`<button class="topicCard" onclick="openTopic(${i})"><span>${t.icon}</span><small>${t.subject}</small><b>${t.topic}</b><em>Interactive simulation →</em></button>`).join("")})})();