const quiz=[
{q:"If force doubles and mass stays the same, acceleration:",a:["halves","doubles","stays the same"],c:1},
{q:"If mass doubles while force stays the same, acceleration:",a:["doubles","halves","stays the same"],c:1},
{q:"A force is best described as:",a:["a push or pull","only movement","only mass"],c:0},
{q:"Which is an example of applying the concept?",a:["Predicting motion after changing mass","Copying a definition","Memorising a formula"],c:0}];
document.getElementById("quiz").innerHTML=quiz.map((x,i)=>`<div class="question"><p>${i+1}. ${x.q}</p>${x.a.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${a}</label>`).join("")}</div>`).join("");
function updateSim(){const f=+force.value,m=+mass.value,a=f/m;fVal.textContent=f+" N";mVal.textContent=m+" kg";acc.textContent=a.toFixed(2)+" m/s²";car.style.left=(10+Math.min(a/2.5,1)*72)+"%";forceLabel.textContent=f+" N →";discovery.textContent=a>1.2?"More force produced greater acceleration.":a<.8?"More mass reduced acceleration.":"Change one variable and compare."}
force.oninput=mass.oninput=updateSim;updateSim();
function completeExperiment(){experimentXP.textContent="+20 XP earned ✓";alert("Mission progress saved! +20 XP • Experiment completed.");}
function submitQuiz(){let s=0;quiz.forEach((x,i)=>{const p=document.querySelector(`input[name=q${i}]:checked`);if(p&&+p.value===x.c)s++});let pct=Math.round(s/quiz.length*100),level=pct<50?"🔴 Remedial Support":pct<75?"🟡 Developing":pct<90?"🟢 Grade-level":"🔵 Advanced";document.getElementById("quizResult").innerHTML=`<div style="margin-top:15px;padding:13px;background:#f0f4fb;border-radius:10px;font-size:12px"><b>Score ${s}/${quiz.length} • ${pct}%</b><br><span style="color:#60708a">${level}</span><br><small style="color:#7a879a">${pct<75?"Targeted practice recommended before advancing.":"Next challenge unlocked."}</small></div>`}
function challenge(btn,correct){document.querySelectorAll(".answers button").forEach(b=>b.disabled=true);const m=document.getElementById("challengeMsg");if(correct){btn.style.background="#e8f3eb";btn.style.color="#3d6f4c";m.innerHTML="<div style='color:#4b805b;font-size:10px;margin-top:8px'>✓ Correct! +50 XP • Challenge complete.</div>"}else{btn.style.background="#faecec";m.innerHTML="<div style='color:#a25454;font-size:10px;margin-top:8px'>Try again in Practice Arena. The force–acceleration relationship is the clue.</div>"}}
function showTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));const map={home:0,learn:1,practice:2,path:3,badges:4,school:5};document.querySelectorAll(".nav")[map[id]].classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function toggleMode(){document.body.classList.toggle("focus-mode");}