let selectedCategory="Matriculation",selectedGrade=null,selectedSubject=null,currentSim=null;
const subjects=[
{name:"English",icon:"📚",desc:"Language, comprehension and communication",sim:"Language Lab"},
{name:"Science",icon:"🧪",desc:"Explore concepts through interactive experiments",sim:"Science Lab"},
{name:"Mathematics",icon:"📐",desc:"Visualise, solve and apply mathematical ideas",sim:"Math Lab"},
{name:"Social Science",icon:"🌍",desc:"Explore maps, history, society and systems",sim:"Social Science Lab"}];
const senior=[{name:"Physics",icon:"⚛️"},{name:"Chemistry",icon:"🧪"},{name:"Botany",icon:"🌿"},{name:"Zoology",icon:"🫀"}];
const students=["Aarav","Ananya","Arjun","Diya","Kavin","Meera","Nila","Rahul","Sanjay","Varsha"];
function selectCategory(btn){document.querySelectorAll(".category").forEach(x=>x.classList.remove("active"));btn.classList.add("active");selectedCategory=btn.dataset.category}
function enterSchool(){let n=document.getElementById("schoolName").value.trim()||"ABC School";document.getElementById("headerSchool").textContent=n;document.getElementById("welcomeTitle").textContent=n;document.getElementById("categoryLabel").textContent=selectedCategory;show("schoolHome")}
function logout(){show("login")}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function gradeCards(){document.getElementById("gradeGrid").innerHTML=Array.from({length:10},(_,i)=>{let g=i+3;let label=g<=5?"Foundation":g<=8?"Core + Competitive":g<=10?"Board + Foundation":"Senior Secondary";return `<button class="grade" onclick="chooseGrade(${g})"><b>Grade ${g}</b><span>${label}</span><div class="mini">Open learning hub →</div></button>`}).join("")}
gradeCards();
function chooseGrade(g){selectedGrade=g;document.getElementById("selectedGradeLabel").textContent=g;document.getElementById("subjectsTitle").textContent=`Grade ${g} • Learning Hub`;document.getElementById("subjectSubtitle").textContent=`${selectedCategory} curriculum • Select a subject to explore its simulation and assessment.`;document.getElementById("neetNotice").classList.toggle("hidden",g!==7);renderSubjects();show("subjects")}
function renderSubjects(){document.getElementById("subjectGrid").innerHTML=subjects.map(s=>`<div class="subject-card" onclick="openSimulation('${s.name}')"><div class="icon">${s.icon}</div><h3>${s.name}</h3><p>${s.desc}</p><div class="launch">▶ ${s.sim} • 20-question assessment</div></div>`).join("")}
function openSimulation(s){selectedSubject=s;currentSim=s;document.getElementById("simTitle").textContent=`Grade ${selectedGrade} • ${s}`;document.getElementById("simDescription").textContent="Explore the concept through an interactive simulation before taking the assessment.";document.getElementById("simBadge").textContent=(subjects.find(x=>x.name===s)?.sim||"SUBJECT LAB").toUpperCase();renderSim(s);renderRemaining();show("simulation")}
function renderRemaining(){document.getElementById("remainingSubjects").innerHTML=subjects.filter(x=>x.name!==selectedSubject).map(x=>`<div class="remaining-item"><span>${x.icon} ${x.name}</span><b onclick="openSimulation('${x.name}')" style="cursor:pointer;color:#5875ad">Open →</b></div>`).join("")}
function renderSim(s){const c=document.getElementById("simCanvas"),controls=document.getElementById("simControls");document.getElementById("simObjective").textContent=`Investigate ${s} through observation, interaction and prediction.`;document.getElementById("simConcept").textContent=`The student interacts with a model, changes variables and observes outcomes. The activity prepares the learner for the 20-question competency assessment.`;controls.innerHTML="";if(s==="Science"){c.innerHTML='<div class="sim-shape atom"></div><div class="sim-shape" style="left:47%;top:43%;font-weight:900;color:#3d557d">Atom</div>';controls.innerHTML='<div class="sim-control"><label>Energy <b id="c1">5</b></label><input id="r1" type="range" min="1" max="10" value="5" oninput="genericSim()"></div><div class="sim-control"><label>Particles <b id="c2">5</b></label><input id="r2" type="range" min="1" max="10" value="5" oninput="genericSim()"></div>';document.getElementById("simObservation").textContent="Increase energy and observe particle activity."}
else if(s==="Mathematics"){c.innerHTML='<div class="sim-shape fraction">3<br><hr>4</div>';controls.innerHTML='<div class="sim-control"><label>Numerator <b id="c1">3</b></label><input id="r1" type="range" min="1" max="9" value="3" oninput="genericSim()"></div><div class="sim-control"><label>Denominator <b id="c2">4</b></label><input id="r2" type="range" min="2" max="10" value="4" oninput="genericSim()"></div>';document.getElementById("simObservation").textContent="Change numerator and denominator to compare fractions."}
else if(s==="English"){c.innerHTML='<div class="sim-shape" style="left:30%;top:30%;font-size:90px">📖</div><div class="sim-shape" style="left:54%;top:38%;font-size:35px">A → B → C</div>';controls.innerHTML='<div class="sim-control"><label>Reading level <b id="c1">3</b></label><input id="r1" type="range" min="1" max="6" value="3" oninput="genericSim()"></div><div class="sim-control"><label>Vocabulary <b id="c2">5</b></label><input id="r2" type="range" min="1" max="10" value="5" oninput="genericSim()"></div>';document.getElementById("simObservation").textContent="Build a story sequence and identify the strongest vocabulary."}
else {c.innerHTML='<div class="sim-shape map-sim">🗺️</div>';controls.innerHTML='<div class="sim-control"><label>Scale <b id="c1">5</b></label><input id="r1" type="range" min="1" max="10" value="5" oninput="genericSim()"></div><div class="sim-control"><label>Distance <b id="c2">5</b></label><input id="r2" type="range" min="1" max="10" value="5" oninput="genericSim()"></div>';document.getElementById("simObservation").textContent="Change scale and distance to explore map interpretation."}}
function genericSim(){let a=document.getElementById("r1").value,b=document.getElementById("r2").value;document.getElementById("c1").textContent=a;document.getElementById("c2").textContent=b;document.getElementById("simObservation").textContent=`You changed the simulation: variable 1 = ${a}, variable 2 = ${b}. Predict the outcome before continuing.`}
function completeSimulation(){toast("Simulation completed ✓ • Learning evidence recorded");}
function openAssessment(){document.getElementById("assessmentTitle").textContent=`Grade ${selectedGrade} • ${selectedSubject} Assessment`;document.getElementById("assessmentGrade").textContent=selectedGrade;document.getElementById("assessmentSubject").textContent=selectedSubject;renderQuestions();renderOMR();show("assessment")}
const qTemplates=[
["Which statement best describes the concept explored in this lesson?",["It can be observed and tested","It can never change","It only requires memorisation","It has no practical use"],0],
["Which approach demonstrates application?",["Copying a definition","Predicting an outcome before testing","Skipping the experiment","Memorising a word"],1],
["What should a learner do when the result is unexpected?",["Ignore it","Change everything at once","Observe, question and test again","Stop learning"],2],
["Which skill is being measured most directly?",["Reasoning and application","Handwriting","Attendance","Typing speed"],0]];
function renderQuestions(){let arr=Array.from({length:20},(_,i)=>qTemplates[i%qTemplates.length]);document.getElementById("questions").innerHTML=arr.map((q,i)=>`<div class="question"><h4>${i+1}. ${q[0]}</h4>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${String.fromCharCode(65+j)}. ${o}</label>`).join("")}</div>`).join("")}
function submitAssessment(){let score=0;for(let i=0;i<20;i++){let p=document.querySelector(`input[name=q${i}]:checked`);if(p&&+p.value===qTemplates[i%4][2])score++}let pct=Math.round(score/20*100);let level=pct<40?"Remedial":pct<60?"Developing":pct<80?"Grade-level":"Advanced";document.getElementById("assessmentResult").innerHTML=`<div style="margin-top:15px;padding:15px;background:#eef3fa;border-radius:10px;font-size:11px"><b>Assessment result: ${score}/20 • ${pct}%</b><br>Learning level: <b>${level}</b><br><small>${level==="Remedial"?"Targeted remedial support recommended.":level==="Advanced"?"Eligible for advanced/competitive practice.":"Continue adaptive practice and reassess."}</small><br><button class="primary" style="margin-top:10px" onclick="openMatrix()">View 10-Student Assessment Matrix →</button></div>`}
function assessmentMode(mode,btn){document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.getElementById("onlineAssessment").classList.toggle("hidden",mode!=="online");document.getElementById("omrAssessment").classList.toggle("hidden",mode!=="omr")}
function renderOMR(){let qs=Array.from({length:20},(_,i)=>`<div class="omr-q"><b>${i+1}</b><div class="bubbles">○A ○B ○C ○D</div></div>`).join("");document.getElementById("omrSheet").innerHTML=`<div class="omr-title"><h3>JSkills Learning • Student OMR Answer Sheet</h3><small>Grade ${selectedGrade} • ${selectedSubject} • ${selectedCategory}</small></div><div class="omr-meta"><span>Student Name: __________________</span><span>Class: __________</span><span>Roll No: __________</span><span>Date: __________</span></div><div class="omr-table">${qs}</div><p style="font-size:8px;color:#777">Instruction: Shade one option completely for each question. Do not mark multiple answers.</p>`}
function printOMR(){let w=window.open("","_blank");w.document.write(`<html><head><title>JSkills OMR Answer Sheet</title><style>body{font-family:Arial;padding:25px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.q{border:1px solid #bbb;padding:8px;font-size:12px}.b{font-size:14px;letter-spacing:3px}h2{text-align:center}@media print{button{display:none}}</style></head><body><h2>JSkills Learning — OMR Answer Sheet</h2><p>Grade ${selectedGrade} • ${selectedSubject} • ${selectedCategory}</p><p>Student: ____________________ &nbsp; Class: __________ &nbsp; Roll No: ________</p><div class="grid">${Array.from({length:20},(_,i)=>`<div class="q"><b>${i+1}</b><div class="b">○ A &nbsp; ○ B &nbsp; ○ C &nbsp; ○ D</div></div>`).join("")}</div><p>Shade one answer per question.</p><script>window.print()<\/script></body></html>`);w.document.close()}
function omrUploaded(input){if(input.files.length)toast("OMR scan selected ✓ • Production version can process the sheet automatically.");}
function openMatrix(){document.getElementById("matrixContext").textContent=`Grade ${selectedGrade} • ${selectedSubject} • 20-question assessment`;let data=[72,61,84,45,78,92,56,67,88,39];document.querySelector("#matrixTable tbody").innerHTML=students.map((s,i)=>{let p=data[i],level=p<50?"Remedial":p<65?"Developing":p<80?"Grade-level":"Advanced",cls=level==="Remedial"?"red":level==="Developing"?"yellow":level==="Grade-level"?"green":"blue";return `<tr><td><b>${s}</b></td><td class="score">${Math.min(99,p+6)}%</td><td class="score">${Math.max(35,p-3)}%</td><td class="score">${Math.max(30,p-8)}%</td><td>✓ Complete</td><td class="score">${p}%</td><td><span class="level-pill ${cls}">${level}</span></td><td>${level==="Remedial"?"Targeted support":level==="Advanced"?"Olympiad pathway":"Adaptive practice"}</td></tr>`}).join("");show("matrix")}
function openStudentDetail(){toast("Demo: student profile opened for selected learner.");}
function showNeet(){show("neet")}
function startNeetSubject(s){selectedSubject=s;toast(`${s} Foundation module selected for Grade 7.`)}
function backToGrades(){show("schoolHome")}
function backToSubjects(){show("subjects")}
function backToSimulation(){show("simulation")}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
