(()=>{"use strict";const T=window.JSKILLS_TOPICS||[];let boardName="CBSE",selected=null,qi=0,score=0;const students=["Aarav","Ananya","Arjun","Diya","Kavin","Meera","Nila","Rahul","Sanjay","Varsha"];const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");scrollTo(0,0)}
function chooseBoard(b,v){document.querySelectorAll(".board").forEach(x=>x.classList.remove("active"));b.classList.add("active");boardName=v}
function enterSchool(){let n=$("schoolName").value.trim()||"ABC School";$("schoolChip").textContent=n+" • "+boardName;$("schoolTitle").textContent=n;$("boardText").textContent=boardName+" • Grade 4";let ss=[...new Set(T.map(x=>x.s))];$("subjectGrid").innerHTML=ss.map(s=>`<div class="subject-card" onclick="openSubject('${s.replace(/'/g,"\\'")}')"><div class="icon">${s==="Mathematics"?"📐":s==="The World Around Us"?"🌍":"📚"}</div><span class="eyebrow">GRADE 4</span><h3>${s}</h3><p>${T.filter(x=>x.s===s).length} topic mission${T.filter(x=>x.s===s).length>1?"s":""} • external activity • 20-question quiz</p><b style="font-size:9px;color:#5875ad">Open subject →</b></div>`).join("");show("home")}
function openSubject(s){$("subjectName").textContent=s;$("topicGrid").innerHTML=T.filter(x=>x.s===s).map(t=>`<div class="topic" onclick='openTopic(${JSON.stringify(t)})'><div class="icon">${s==="Mathematics"?"📐":s==="The World Around Us"?"🌍":"📚"}</div><span class="eyebrow">${t.c}</span><h3>${t.t}</h3><p>Matched external resource: <b>${t.tech}</b>. Then JSkills gives a topic-specific 20-question quiz.</p><span class="tech">▶ Open simulation</span></div>`).join("");show("topics")}
function openTopic(t){selected=t;$("labTech").textContent=t.tech.toUpperCase();$("labTitle").textContent=`Grade 4 • ${t.s}`;$("labTopic").textContent=`${t.c} — ${t.t}`;$("objective").textContent=t.objective;$("externalName").textContent=t.tech;$("externalLink").href=t.url;$("externalFrame").src=t.url;$("steps").innerHTML=[`Open and explore the ${t.tech} activity.`,`Try at least two interactions or changes.`,`Observe what happens and connect it to the topic.`,`Return to JSkills and complete all 20 questions.`].map(x=>`<li>${x}</li>`).join("");show("lab")}
function startQuiz(){qi=0;score=0;$("quizTitle").textContent=`${selected.c} • ${selected.t}`;renderQuestion();show("quiz")}
function renderQuestion(){let q=selected.questions[qi];$("qCount").textContent=`Question ${qi+1} of 20`;$("qXP").textContent=score*5;$("bar").style.width=(qi/20*100)+"%";$("question").innerHTML=`<h3>${q[0]}</h3>`+q[1].map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}"> ${String.fromCharCode(65+i)}. ${o}</label>`).join("")}
function submitAnswer(){let a=document.querySelector('input[name="answer"]:checked');if(!a){alert("Please choose an answer.");return}if(+a.value===selected.questions[qi][2])score++;if(qi<19){qi++;renderQuestion()}else finish()}
function skipQuestion(){if(qi<19){qi++;renderQuestion()}else finish()}
function finish(){let p=score*5,b=p>=80?"Mastery Champion":p>=60?"Skill Builder":"Retry Explorer";$("score").textContent=p+"%";$("badgeTitle").textContent=b;$("badge").textContent=b;$("earnedXP").textContent=50+score*5;$("badgeText").textContent=p>=80?"Strong evidence of topic mastery. Advanced practice can be recommended.":p>=60?"Developing toward mastery. Adaptive practice recommended.":"Retry the simulation with teacher support.";$("concept").textContent=Math.min(99,p+8)+"%";$("application").textContent=p+"%";$("reasoning").textContent=Math.max(30,p-5)+"%";$("problem").textContent=Math.max(30,p-8)+"%";$("resultTitle").textContent=`${selected.t} • Mission Complete`;show("result")}
function showMatrix(){let vals=[82,61,76,45,88,92,54,69,84,39];$("matrixBody").innerHTML=students.map((s,i)=>{let p=vals[i],l=p<50?"Remedial":p<65?"Developing":p<80?"Grade-level":"Advanced",c=l==="Remedial"?"red":l==="Developing"?"yellow":l==="Grade-level"?"green":"blue";return`<tr><td><b>${s}</b></td><td>${Math.min(99,p+7)}%</td><td>${Math.max(35,p-2)}%</td><td>${Math.max(30,p-8)}%</td><td>${Math.max(32,p-5)}%</td><td><b>${p}%</b></td><td><span class="pill ${c}">${l}</span></td><td>${l==="Remedial"?"Targeted remedial":l==="Advanced"?"🏆 Olympiad Foundation":"Adaptive practice"}</td></tr>`}).join("");$("matrixContext").textContent=`Grade 4 • ${selected.s} • ${selected.t}`;show("matrix")}
window.show=show;window.chooseBoard=chooseBoard;window.enterSchool=enterSchool;window.openSubject=openSubject;window.openTopic=openTopic;window.startQuiz=startQuiz;window.submitAnswer=submitAnswer;window.skipQuestion=skipQuestion;window.showMatrix=showMatrix;})();
