(()=>{"use strict";const T=window.JSKILLS_TOPICS||[];let boardName="CBSE",selected=null,qi=0,score=0;const students=["Aarav","Ananya","Arjun","Diya","Kavin","Meera","Nila","Rahul","Sanjay","Varsha"];const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");scrollTo(0,0)}
function board(b,v){document.querySelectorAll(".board").forEach(x=>x.classList.remove("active"));b.classList.add("active");boardName=v}
function enter(){let n=$("schoolName").value.trim()||"ABC School";$("schoolChip").textContent=n+" • "+boardName;$("schoolTitle").textContent=n;$("boardText").textContent=boardName+" • Grade 3";let ss=[...new Set(T.map(x=>x.s))];$("subjects").innerHTML=ss.map(s=>`<div class="subject" onclick="openSubject('${s.replace(/'/g,"\\'")}')"><div class="icon">${s==="Mathematics"?"📐":s==="The World Around Us"?"🌍":"📚"}</div><span class="eyebrow">GRADE 3</span><h3>${s}</h3><p>${T.filter(x=>x.s===s).length} topic missions • external activity • 20-question quiz</p><b style="font-size:9px;color:#5875ad">Open subject →</b></div>`).join("");show("home")}
function openSubject(s){$("subName").textContent=s;$("topicGrid").innerHTML=T.filter(x=>x.s===s).map(t=>`<div class="topic" onclick='openTopic(${JSON.stringify(t)})'><div class="icon">${s==="Mathematics"?"📐":s==="The World Around Us"?"🌍":"📚"}</div><span class="eyebrow">${t.c}</span><h3>${t.t}</h3><p><b>${t.tech}</b> activity → then a topic-specific 20-question quiz.</p><span class="tech">▶ Open simulation</span></div>`).join("");show("topics")}
function openTopic(t){selected=t;$("tech").textContent=t.tech.toUpperCase();$("labTitle").textContent=`Grade 3 • ${t.s}`;$("labTopic").textContent=`${t.c} — ${t.t}`;$("objective").textContent=t.objective;$("externalName").textContent=t.tech;$("openLink").href=t.url;$("frame").src=t.url;$("steps").innerHTML=[`Open the external ${t.tech} activity.`,`Try at least two changes or interactions.`,`Observe and explain what happens.`,`Return here for the 20-question quiz.`].map(x=>`<li>${x}</li>`).join("");show("lab")}
function startQuiz(){qi=0;score=0;$("quizTitle").textContent=`${selected.c} • ${selected.t}`;renderQ();show("quiz")}
function renderQ(){let q=selected.questions[qi];$("qno").textContent=`Question ${qi+1} of 20`;$("fill").style.width=(qi/20*100)+"%";$("question").innerHTML=`<h3>${q[0]}</h3>`+q[1].map((o,i)=>`<label class="option"><input type="radio" name="a" value="${i}"> ${String.fromCharCode(65+i)}. ${o}</label>`).join("")}
function answer(){let a=document.querySelector('input[name="a"]:checked');if(!a){alert("Please choose an answer.");return}if(+a.value===selected.questions[qi][2])score++;$("qxp").textContent=score*5;if(qi<19){qi++;renderQ()}else finish()}
function skip(){if(qi<19){qi++;renderQ()}else finish()}
function finish(){let p=score*5,b=p>=80?"Mastery Champion":p>=60?"Skill Builder":"Retry Explorer";$("score").textContent=p+"%";$("badgeTitle").textContent=b;$("badge").textContent=b;$("earned").textContent=score*5+50;$("badgeText").textContent=p>=80?"Strong evidence of topic mastery.":p>=60?"Developing toward mastery.":"Retry the simulation with teacher support.";$("cc").textContent=Math.min(99,p+10)+"%";$("ca").textContent=p+"%";$("cr").textContent=Math.max(30,p-5)+"%";$("cp").textContent=Math.max(30,p-8)+"%";$("resultTitle").textContent=`${selected.t} • Mission Complete`;show("result")}
function matrix(){let vals=[72,61,84,45,78,92,56,67,88,39];$("tbody").innerHTML=students.map((s,i)=>{let p=vals[i],l=p<50?"Remedial":p<65?"Developing":p<80?"Grade-level":"Advanced",c=l==="Remedial"?"red":l==="Developing"?"yellow":l==="Grade-level"?"green":"blue";return`<tr><td><b>${s}</b></td><td>${Math.min(99,p+7)}%</td><td>${Math.max(35,p-2)}%</td><td>${Math.max(30,p-8)}%</td><td>${Math.max(32,p-5)}%</td><td><b>${p}%</b></td><td><span class="pill ${c}">${l}</span></td><td>${l==="Remedial"?"Targeted remedial":l==="Advanced"?"🏆 Olympiad Foundation":"Adaptive practice"}</td></tr>`}).join("");$("mctx").textContent=`Grade 3 • ${selected.s} • ${selected.t}`;show("matrix")}
window.show=show;window.board=board;window.enter=enter;window.openSubject=openSubject;window.openTopic=openTopic;window.startQuiz=startQuiz;window.answer=answer;window.skip=skip;window.matrix=matrix;})();
